// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjajShbAkFm7-SrpQLteGxPO7NRIEP0b0',
    appId: '1:252028585148:web:98ec1579242261514b7cb9',
    messagingSenderId: '252028585148',
    projectId: 'ixl-project-a35c1',
    authDomain: 'ixl-project-a35c1.firebaseapp.com',
    storageBucket: 'ixl-project-a35c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEUcfu6AIE4X58e12AGDdAEomYNlbBicI',
    appId: '1:252028585148:android:833733e2b2f562f64b7cb9',
    messagingSenderId: '252028585148',
    projectId: 'ixl-project-a35c1',
    storageBucket: 'ixl-project-a35c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAShAJkGrARDSC4M8zopJj5Fk8oSQwpNbQ',
    appId: '1:252028585148:ios:9974f5eea2595a924b7cb9',
    messagingSenderId: '252028585148',
    projectId: 'ixl-project-a35c1',
    storageBucket: 'ixl-project-a35c1.appspot.com',
    iosBundleId: 'kz.katev.ixl.ixl',
  );
}
