// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuFGoxLw-e4j0ZxhcquARn0kAVaWEyjP8',
    appId: '1:1010539929098:web:2179002e2f09c48f6989f3',
    messagingSenderId: '1010539929098',
    projectId: 'ixl-4123b',
    authDomain: 'ixl-4123b.firebaseapp.com',
    storageBucket: 'ixl-4123b.appspot.com',
    measurementId: 'G-G06YEGF0NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAotP27A2zxLm00qh1PjKKTfr3zhiZlTUY',
    appId: '1:1010539929098:android:fe9762b7474a5b616989f3',
    messagingSenderId: '1010539929098',
    projectId: 'ixl-4123b',
    storageBucket: 'ixl-4123b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE5-qFovjJgX_b_SgSO1gc3CmvtURcL08',
    appId: '1:1010539929098:ios:2aaf42c67dfd9dbe6989f3',
    messagingSenderId: '1010539929098',
    projectId: 'ixl-4123b',
    storageBucket: 'ixl-4123b.appspot.com',
    iosBundleId: 'kz.katev.ixl.ixl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE5-qFovjJgX_b_SgSO1gc3CmvtURcL08',
    appId: '1:1010539929098:ios:18b8ce5feab32bfd6989f3',
    messagingSenderId: '1010539929098',
    projectId: 'ixl-4123b',
    storageBucket: 'ixl-4123b.appspot.com',
    iosBundleId: 'com.example.ixl.RunnerTests',
  );
}
